### ISSUE TITLE
Question: What is “CRD” in the context of Artifactory?

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/bcbb-gitops-docs#3]
Refer to: https://github.com/bcgov/bcbb-gitops-docs/blob/main/docs/03-artifactory.md

Q: What is Artifactory “CRD”?  Container Registry ___, or ....? 

Re: "**Note**: It's important that this CRD resource gets created in the tools namespace." Please state why this is important.

**Comment by sylus** [comment]
Hi @NicoledeGreef CRD stands for Custom Resource Definition and is what you use when you want to extend the Kubernetes API.

This was installed in the tools namespace since it was mentioned in the BC Gov artifactory documentation where it needs to exist in order to properly setup the Artifactory connection.

https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/build-deploy-and-maintain-apps/setup-artifactory-project-repository/

I can update the docs to reflect this. :)

**Comment by sylus** [comment]
Resolved this in my updates notes :D
